### ISSUE TITLE
Pythonic None should be preferred to 'None' in checksum arg for BloscpackArgs

### ISSUE THREAD

**Issue by FrancescAlted** [Blosc/bloscpack#11]
The subject says it all.

**Comment by oogali** [comment]
This seems like an easy change to make, but wouldn't one have to maintain compatibility with all the people that actually have the 'None' string in their code?

**Comment by esc** [comment]
Probably both should be possible. The reason it is a string is because that string is then written into the header. At the time, I thought that this would be a consistent albeit non-pythonic approach.

**Comment by oogali** [comment]
If one does make the change to None, in the places where it's written into the header, would it make sense to just "re-cast" it with `str`? (as that will convert None to 'None')

For example:

```
-         self.checksum        = checksum
+         self.checksum        = str(checksum)
```

There'd probably need to be some logic on the inbound read along the lines of `if value == 'None': value = None`.
