### ISSUE TITLE
Release the GIL

### ISSUE THREAD

**Issue by mrocklin** [Blosc/bloscpack#34]
I would like to use single-threaded `bloscpack` in many threads in parallel.  My understanding is that this is possible in the C layer by creating many contexts but not currently possible in the Python layer.

**Comment by esc** [comment]
As of v1.2.5 the python-blosc wrapper keeps the GIL:

https://github.com/Blosc/python-blosc/blob/master/RELEASE_NOTES.rst

Support for contexts isn't supported yet (I believe).

**Comment by mrocklin** [comment]
Should I raise a similar issue at python-blosc?

**Comment by esc** [comment]
Probably in python-blosc is better than here, since bloscpack depends on that.

**Comment by esc** [comment]
Closing, since bloscpack doesn't go down to that level.
