### ISSUE TITLE
compat_util.py file is not added

### ISSUE THREAD

**Issue by ghislainp** [Blosc/bloscpack#36]
in python3, 

  File "anaconda3/lib/python3.4/site-packages/bloscpack/headers.py", line 17, in <module>
    from .compat_util import (OrderedDict,
ImportError: No module named 'bloscpack.compat_util'

**Comment by esc** [comment]
yeah, master is broken right now, I'll fix it shortly.

**Comment by esc** [comment]
master is green again, note also, that python3 support isn't available from master yet.
