### ISSUE TITLE
wheel package format

### ISSUE THREAD

**Issue by stonebig** [Blosc/bloscpack#44]
would it be possible to get bloscpack as a wheel on pypi ?

**Comment by esc** [comment]
Not sure what advantage this would brin? Bloscpack is pure Python. Perhaps you want a wheel for python-blosc, the Python C-API based interface to Blosc?

**Comment by stonebig** [comment]
having wheels simplify the user of "requirement" files with pip.

**Comment by esc** [comment]
@stonebig sorry, I don't understand what you mean, could you elaborate please.

**Comment by stonebig** [comment]
Suppose:
- package A is a .tar.gz package,
- package B is a wheel package,
- package A uses package B during setup.

In that case, I have to:
- do a pip 'requirement' with package B,
- then only aftern a second pip 'requirement' with package A.

Indeed pip will first try to transform A package into a wheel, before resolving dependancies, and so need package B to be already installed.

That is one of the disadvantage of not having wheel packages, even for non-binary packages.

**Comment by esc** [comment]
I'm not sure I understand this still. I don't really know what a `.tar.gz` package is I'm afraid.

**Comment by stonebig** [comment]
pypi.python.org/packages/source/b/bloscpack/bloscpack-0.9.0`.tar.gz`

**Comment by esc** [comment]
Hmmm, interesting.

**Comment by esc** [comment]
Hey, I just made a wheel for 0.12.0:

https://pypi.org/project/bloscpack/#files


Hope this helps and closing issue now.

**Comment by esc** [comment]
Here is how it is done:

https://github.com/Blosc/bloscpack/commit/c189f6fc079a1997c29605b10bbd0b2cf518e54b
