### ISSUE TITLE
Bloscpack massively broken with python-blosc 1.2.8

### ISSUE THREAD

**Issue by esc** [Blosc/bloscpack#45]
There are a multitude of errors when testing bloscpack with python-blosc 1.2.8 (even a segmentation fault):

https://travis-ci.org/Blosc/bloscpack/jobs/76175299

**Comment by FrancescAlted** [comment]
The errors you are referring to [were fixed in 1.3.1](https://github.com/Blosc/python-blosc/blob/master/RELEASE_NOTES.rst).  Regarding the segfaults, they seem to be gone in the latest releases too.

**Comment by esc** [comment]
Okay, did you opt for doing less compiler optimization during compile?

**Comment by esc** [comment]
Haha, 1.2.7 now yields errors on my new machine, looks like it didn't compile correctly. Segfaults seem to be gone too for 2.7.

**Comment by esc** [comment]
```
ImportError: /home/esc/git/bloscpack/.venv3/lib/python3.5/site-packages/blosc/blosc_extension.cpython-35m-x86_64-linux-gnu.so: undefined symbol: __cpu_model
```

**Comment by esc** [comment]
The only errors I see from bloscpack with 1.3.3 are related to hardcoded offsets in the test etc... Can it be that the performance of the default compressor was weakend? Or maybe it uses different defaults that lead to less performance?

**Comment by FrancescAlted** [comment]
I did reduce the optimization level initially yes.  However, other people (@alimanfoo) told me that using -O3 was fine again with latest releases of Blosc, so I get back to use maximum optimization (-O3) and never got a segfault afterwards.

Regarding the hardcoded offsets, yeas, Blosc is a living thing with small improvements happening all the time, and that can lead to different performance.  Hence, and IMO, bloscpack should be more relaxed on the compression ratios it should expect from the different codecs inside Blosc.

**Comment by esc** [comment]
Closing as of #51
