### ISSUE TITLE
Adopt the new code-of-conduct

### ISSUE THREAD

**Issue by esc** [Blosc/bloscpack#78]
https://github.com/Blosc/CodeOfConduct/blob/master/README.md

**Comment by brlcad** [comment]
now a dead link

**Comment by esc** [comment]
@brlcad thabk you for reporting this, any chance you could prep a pull-request to fix this?

**Comment by brlcad** [comment]
Sorry, don't know where the right link is.  Found a few references to Blosc/CodeOfConduct in a couple repos.  Search only found that too.  Only noticed because it was referenced in the c-blosc repo.
