### ISSUE TITLE
Can we save dictionary including numpy arrays ?

### ISSUE THREAD

**Issue by MyraBaba** [Blosc/bloscpack#95]
Hi,

I tested to save dicttionar consisting of two numpy arrays .

it says

dict object has no attribute 'dtype'

array is:
```

  `_names_np = np.empty(shape=[number_of_item, ], dtype='<U254')

    _floats_np = np.empty(shape=[number_of_item, 512], dtype=np.float32)`
```

**Comment by esc** [comment]
@MyraBaba thanks for asking about this! This functionality isn't supported at the moment, I am afraid. You will have to save each numpy array individually for the time being..

**Comment by MyraBaba** [comment]
It  could be very usefull :)

Best

Thx

**Comment by MyraBaba** [comment]
What is the proper way to save ndarrays including strings : 

Like

people_names_np = np.empty(shape=[number_of_item, ], dtype='object')

Gives ObjectNumpyarray rejection

**Comment by MyraBaba** [comment]
When I change the dtype to <U254 it gives : 

ValueError: 'typesize' must be in the range 0 <= n <= 255, not '1008'

**Comment by esc** [comment]
@MyraBaba thanks again for asking about this, unfortunately however, object arrays and unicode arrays are not supported to my knowledge.

**Comment by esc** [comment]
I am closing this as I believe it has been resolved.Thank you for using bloscpack!
