### ISSUE TITLE
Port testing from nose to pytest

### ISSUE THREAD

**Issue by mcepl** [Blosc/bloscpack#99]
I am a maintainer of Python packages in openSUSE, and I am on my crusade of eliminating nose1 from our distribution. When I look at its repository on https://github.com/nose-devs/nose, the last release 1.3.7 was on 2 Jun 2015, and even the last commit on the master branch was on 4 Mar 2016. Also, nose won't be supported starting with Python 3.9/3.10.

[This patch](https://github.com/Blosc/bloscpack/files/5034520/remove_nose.patch.txt) eliminates dependency on nose. Resulting test suite depends on pytest, which is currently perfectly developed and maintained.

Unfortunately, I wasn’t able to test it properly, because the rest of the test suite seems to me to be in pretty bad shape (#98 is I am afraid just one example of many), so I have to leave this patch as is in whatever shape it is.

**Comment by esc** [comment]
thanks for the patch, I will incorporate it as and when I revive this package (hopefully soon).

**Comment by esc** [comment]
CI for `master` is green again, please feel free to kick-off a PR with the patch.

**Comment by esc** [comment]
Adopted via #103

**Comment by esc** [comment]
@mcepl thank you again for submitting this.
